### ISSUE TITLE
XMath.Pow, XMath.Exp etc. don't work

### ISSUE THREAD

**Issue by GeoBIM2020** [m4rs-mt/ILGPU.Algorithms#16]
@m4rs-mt 

if XMath.Pow or Math.Pow, and XMath.Exp etc. are used in kernel,  "too many resources requested" error will be thrown if there are too many threads (e.g. 1024 in my case).  No error thrown if I decrease threads (say, 256).  but kernel running will hang on for ever.  There should be something wrong with those complex math function in ILGPU.  

Attached is code for replication the problem.

[WindowsFormsApp1.zip](https://github.com/m4rs-mt/ILGPU/files/4568394/WindowsFormsApp1.zip)

**Comment by m4rs-mt** [comment]
@MoFtZ Can you take a closer look?

**Comment by MoFtZ** [comment]
@toolwtech, thanks for highlighting these issues.

The first issue with "too many resources requested" is due to some recent changes we made to increase the accuracy of `XMath` functions. In particular, some registers/resources were not being used efficiently.

The second issue with the kernel hanging forever is related to edge cases in those `XMath` functions. In particular, your kernel is calling `XMath.Log(0)`, which is undefined.

I'll put up patches to fix these soon.

**Comment by MoFtZ** [comment]
@toolwtech, I've put up some patches to fix most of the issues.

Please note that your kernel is currently calling `XMath.Pow` with a negative base. This is not currently supported by `ILGPU.Algorithms`, but I'll see if I can find a solution.

**Comment by m4rs-mt** [comment]
@toolwtech Based on @MoFtZ's PR and an investigation of the emitted PTX code, the actual problem seems to be related to the PTX assembler. It seems to fail allocating a reasonable number of registers. Have you tried loading your kernel with a `new KernelSpecialization(...)` instance in order to tell the PTX assembler (and ILGPU) to target a specific number of threads per group? This often helps to circumvent problems with the PTX assembler failing to allocate registers.

@MoFtZ I guess it makes sense not to "force-inline" all functions every time. However, it would have been nice 🤓

**Comment by GeoBIM2020** [comment]
@m4rs-mt I've never tried to compile kernel with "new KernelSpecialization.  But it seems "LoadAutoGroupedStreamKernel" can resolve problem of "too meany resources requested". It seems that method can allocate threads automatically based on balance of resources and registers, is my guess right?  usually I like to use "LoadStreamKernel" and define the number of threads to each group, but sometimes "too many resources requested" is thrown out since I don't know how many registered are needed for each thread and assign too many threads for each group.  Hopefully there is ILGPU method that can allow use to know available resources for specific GPU and needed resources for each of kernel so that we can assign the number of threads correctly , or allow the compiler to optimize the number of threads based on resources allocated for each of thread.

**Comment by m4rs-mt** [comment]
@toolwtech Using a `KernelSpecialization` instance tells ILGPU and the PTX assembler to limit its source allocation opportunities to emit final code that is compatible with the intended grid/group configuration.

> Hopefully there is ILGPU method that can allow use to know available resources for specific GPU and needed resources for each of kernel so that we can assign the number of threads correctly ,

This issue is often related to the PTX assembler (inside the GPU driver) that allocates resources in a different way. What we could do is to provide a default functionality that always assumes that the maximum number of threads per group is being used.

**Comment by GeoBIM2020** [comment]
@MoFtZ @m4rs-mt .  I've tested Exp and Pow, both are working properly now. Great work!
